### GET
GET http://localhost:5000

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"

}


###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"

}

### fetch todos
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxNTc0Mzc4LCJleHAiOjE3NTE2NjA3Nzh9.tDVSlKiCEKXacWUZMpKL050kKnv-U_hOeI14ZGvTWME

### create new todo
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxNTc0Mzc4LCJleHAiOjE3NTE2NjA3Nzh9.tDVSlKiCEKXacWUZMpKL050kKnv-U_hOeI14ZGvTWME
Content-Type: application/json

{

    "task": "Finish coding the proj"

}

### Update todo
PUT http://localhost:5000/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxNTc0Mzc4LCJleHAiOjE3NTE2NjA3Nzh9.tDVSlKiCEKXacWUZMpKL050kKnv-U_hOeI14ZGvTWME
Content-Type: application/json

{

    "completed: 1"

}
###
DELETE http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxNTc0Mzc4LCJleHAiOjE3NTE2NjA3Nzh9.tDVSlKiCEKXacWUZMpKL050kKnv-U_hOeI14ZGvTWME



